# SwiftLint Configuration for VOICE

# Paths to include during linting
included:
  - VOICE/VOICE

# Paths to exclude during linting
excluded:
  - VOICE/VOICE/Assets.xcassets
  - VOICE/VOICE.xcodeproj
  - DerivedData
  - build
  - Tests

# Enabled rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - line_length
  - trailing_whitespace

# Rule configurations
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - URL
    - url

type_name:
  min_length: 3
  max_length: 50

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '^\s*print\('
    match_kinds:
      - identifier
    message: "Use Logger instead of print statements"
    severity: warning

  no_force_cast:
    name: "No Force Cast"
    regex: 'as!'
    message: "Use safe casting with 'as?' or 'guard let'"
    severity: error

# Reporter
reporter: "xcode"

